/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RentRouteImport } from './routes/rent'
import { Route as PlotsRouteImport } from './routes/plots'
import { Route as CommercialRouteImport } from './routes/commercial'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as IndexRouteImport } from './routes/index'

const RentRoute = RentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const PlotsRoute = PlotsRouteImport.update({
  id: '/plots',
  path: '/plots',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialRoute = CommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buy': typeof BuyRoute
  '/commercial': typeof CommercialRoute
  '/plots': typeof PlotsRoute
  '/rent': typeof RentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buy': typeof BuyRoute
  '/commercial': typeof CommercialRoute
  '/plots': typeof PlotsRoute
  '/rent': typeof RentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buy': typeof BuyRoute
  '/commercial': typeof CommercialRoute
  '/plots': typeof PlotsRoute
  '/rent': typeof RentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/buy' | '/commercial' | '/plots' | '/rent'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/buy' | '/commercial' | '/plots' | '/rent'
  id: '__root__' | '/' | '/buy' | '/commercial' | '/plots' | '/rent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuyRoute: typeof BuyRoute
  CommercialRoute: typeof CommercialRoute
  PlotsRoute: typeof PlotsRoute
  RentRoute: typeof RentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rent': {
      id: '/rent'
      path: '/rent'
      fullPath: '/rent'
      preLoaderRoute: typeof RentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plots': {
      id: '/plots'
      path: '/plots'
      fullPath: '/plots'
      preLoaderRoute: typeof PlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial': {
      id: '/commercial'
      path: '/commercial'
      fullPath: '/commercial'
      preLoaderRoute: typeof CommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuyRoute: BuyRoute,
  CommercialRoute: CommercialRoute,
  PlotsRoute: PlotsRoute,
  RentRoute: RentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
