/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PostPropertyRouteImport } from './routes/post-property'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandRouteImport } from './routes/land'
import { Route as HiveVerifiedRouteImport } from './routes/hive-verified'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as BuildersRouteImport } from './routes/builders'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as ApartmentsRouteImport } from './routes/apartments'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertyIdRouteImport } from './routes/property.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPropertyRoute = PostPropertyRouteImport.update({
  id: '/post-property',
  path: '/post-property',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandRoute = LandRouteImport.update({
  id: '/land',
  path: '/land',
  getParentRoute: () => rootRouteImport,
} as any)
const HiveVerifiedRoute = HiveVerifiedRouteImport.update({
  id: '/hive-verified',
  path: '/hive-verified',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildersRoute = BuildersRouteImport.update({
  id: '/builders',
  path: '/builders',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartmentsRoute = ApartmentsRouteImport.update({
  id: '/apartments',
  path: '/apartments',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/apartments': typeof ApartmentsRoute
  '/blogs': typeof BlogsRoute
  '/builders': typeof BuildersRoute
  '/buy': typeof BuyRoute
  '/contact': typeof ContactRoute
  '/hive-verified': typeof HiveVerifiedRoute
  '/land': typeof LandRoute
  '/login': typeof LoginRoute
  '/post-property': typeof PostPropertyRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/terms': typeof TermsRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/apartments': typeof ApartmentsRoute
  '/blogs': typeof BlogsRoute
  '/builders': typeof BuildersRoute
  '/buy': typeof BuyRoute
  '/contact': typeof ContactRoute
  '/hive-verified': typeof HiveVerifiedRoute
  '/land': typeof LandRoute
  '/login': typeof LoginRoute
  '/post-property': typeof PostPropertyRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/terms': typeof TermsRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/apartments': typeof ApartmentsRoute
  '/blogs': typeof BlogsRoute
  '/builders': typeof BuildersRoute
  '/buy': typeof BuyRoute
  '/contact': typeof ContactRoute
  '/hive-verified': typeof HiveVerifiedRoute
  '/land': typeof LandRoute
  '/login': typeof LoginRoute
  '/post-property': typeof PostPropertyRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/terms': typeof TermsRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agents'
    | '/apartments'
    | '/blogs'
    | '/builders'
    | '/buy'
    | '/contact'
    | '/hive-verified'
    | '/land'
    | '/login'
    | '/post-property'
    | '/privacy'
    | '/projects'
    | '/terms'
    | '/property/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agents'
    | '/apartments'
    | '/blogs'
    | '/builders'
    | '/buy'
    | '/contact'
    | '/hive-verified'
    | '/land'
    | '/login'
    | '/post-property'
    | '/privacy'
    | '/projects'
    | '/terms'
    | '/property/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agents'
    | '/apartments'
    | '/blogs'
    | '/builders'
    | '/buy'
    | '/contact'
    | '/hive-verified'
    | '/land'
    | '/login'
    | '/post-property'
    | '/privacy'
    | '/projects'
    | '/terms'
    | '/property/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgentsRoute: typeof AgentsRoute
  ApartmentsRoute: typeof ApartmentsRoute
  BlogsRoute: typeof BlogsRoute
  BuildersRoute: typeof BuildersRoute
  BuyRoute: typeof BuyRoute
  ContactRoute: typeof ContactRoute
  HiveVerifiedRoute: typeof HiveVerifiedRoute
  LandRoute: typeof LandRoute
  LoginRoute: typeof LoginRoute
  PostPropertyRoute: typeof PostPropertyRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRoute
  TermsRoute: typeof TermsRoute
  PropertyIdRoute: typeof PropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-property': {
      id: '/post-property'
      path: '/post-property'
      fullPath: '/post-property'
      preLoaderRoute: typeof PostPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/land': {
      id: '/land'
      path: '/land'
      fullPath: '/land'
      preLoaderRoute: typeof LandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hive-verified': {
      id: '/hive-verified'
      path: '/hive-verified'
      fullPath: '/hive-verified'
      preLoaderRoute: typeof HiveVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builders': {
      id: '/builders'
      path: '/builders'
      fullPath: '/builders'
      preLoaderRoute: typeof BuildersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartments': {
      id: '/apartments'
      path: '/apartments'
      fullPath: '/apartments'
      preLoaderRoute: typeof ApartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgentsRoute: AgentsRoute,
  ApartmentsRoute: ApartmentsRoute,
  BlogsRoute: BlogsRoute,
  BuildersRoute: BuildersRoute,
  BuyRoute: BuyRoute,
  ContactRoute: ContactRoute,
  HiveVerifiedRoute: HiveVerifiedRoute,
  LandRoute: LandRoute,
  LoginRoute: LoginRoute,
  PostPropertyRoute: PostPropertyRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRoute,
  TermsRoute: TermsRoute,
  PropertyIdRoute: PropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
