/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as V2_rootRouteImport } from './routes/v2/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PostPropertyRouteImport } from './routes/post-property'
import { Route as LandRouteImport } from './routes/land'
import { Route as HiveVerifiedRouteImport } from './routes/hive-verified'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as BuildersRouteImport } from './routes/builders'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as ApartmentsRouteImport } from './routes/apartments'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as V2IndexRouteImport } from './routes/v2/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as V2PostPropertyRouteImport } from './routes/v2/post-property'
import { Route as V2LandRouteImport } from './routes/v2/land'
import { Route as V2HiveVerifiedRouteImport } from './routes/v2/hive-verified'
import { Route as V2ContactRouteImport } from './routes/v2/contact'
import { Route as V2BuyRouteImport } from './routes/v2/buy'
import { Route as V2ApartmentsRouteImport } from './routes/v2/apartments'
import { Route as V2AdminRouteImport } from './routes/v2/admin'
import { Route as V2AboutRouteImport } from './routes/v2/about'
import { Route as PropertySlugRouteImport } from './routes/property.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as V2AdminIndexRouteImport } from './routes/v2/admin/index'
import { Route as AdminPropertiesIndexRouteImport } from './routes/admin/properties/index'
import { Route as AdminInquiriesIndexRouteImport } from './routes/admin/inquiries/index'
import { Route as V2PropertySlugRouteImport } from './routes/v2/property.$slug'
import { Route as V2AdminLoginRouteImport } from './routes/v2/admin/login'
import { Route as AdminPropertiesNewRouteImport } from './routes/admin/properties/new'
import { Route as V2AdminPropertiesIndexRouteImport } from './routes/v2/admin/properties/index'
import { Route as V2AdminInquiriesIndexRouteImport } from './routes/v2/admin/inquiries/index'
import { Route as V2AdminPropertiesNewRouteImport } from './routes/v2/admin/properties/new'
import { Route as AdminPropertiesIdEditRouteImport } from './routes/admin/properties/$id.edit'
import { Route as V2AdminPropertiesIdEditRouteImport } from './routes/v2/admin/properties/$id.edit'

const V2_rootRoute = V2_rootRouteImport.update({
  id: '/v2/__root',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPropertyRoute = PostPropertyRouteImport.update({
  id: '/post-property',
  path: '/post-property',
  getParentRoute: () => rootRouteImport,
} as any)
const LandRoute = LandRouteImport.update({
  id: '/land',
  path: '/land',
  getParentRoute: () => rootRouteImport,
} as any)
const HiveVerifiedRoute = HiveVerifiedRouteImport.update({
  id: '/hive-verified',
  path: '/hive-verified',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildersRoute = BuildersRouteImport.update({
  id: '/builders',
  path: '/builders',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartmentsRoute = ApartmentsRouteImport.update({
  id: '/apartments',
  path: '/apartments',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const V2IndexRoute = V2IndexRouteImport.update({
  id: '/v2/',
  path: '/v2/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const V2PostPropertyRoute = V2PostPropertyRouteImport.update({
  id: '/v2/post-property',
  path: '/v2/post-property',
  getParentRoute: () => rootRouteImport,
} as any)
const V2LandRoute = V2LandRouteImport.update({
  id: '/v2/land',
  path: '/v2/land',
  getParentRoute: () => rootRouteImport,
} as any)
const V2HiveVerifiedRoute = V2HiveVerifiedRouteImport.update({
  id: '/v2/hive-verified',
  path: '/v2/hive-verified',
  getParentRoute: () => rootRouteImport,
} as any)
const V2ContactRoute = V2ContactRouteImport.update({
  id: '/v2/contact',
  path: '/v2/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const V2BuyRoute = V2BuyRouteImport.update({
  id: '/v2/buy',
  path: '/v2/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const V2ApartmentsRoute = V2ApartmentsRouteImport.update({
  id: '/v2/apartments',
  path: '/v2/apartments',
  getParentRoute: () => rootRouteImport,
} as any)
const V2AdminRoute = V2AdminRouteImport.update({
  id: '/v2/admin',
  path: '/v2/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const V2AboutRoute = V2AboutRouteImport.update({
  id: '/v2/about',
  path: '/v2/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertySlugRoute = PropertySlugRouteImport.update({
  id: '/property/$slug',
  path: '/property/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const V2AdminIndexRoute = V2AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => V2AdminRoute,
} as any)
const AdminPropertiesIndexRoute = AdminPropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesIndexRoute = AdminInquiriesIndexRouteImport.update({
  id: '/inquiries/',
  path: '/inquiries/',
  getParentRoute: () => AdminRoute,
} as any)
const V2PropertySlugRoute = V2PropertySlugRouteImport.update({
  id: '/v2/property/$slug',
  path: '/v2/property/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const V2AdminLoginRoute = V2AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => V2AdminRoute,
} as any)
const AdminPropertiesNewRoute = AdminPropertiesNewRouteImport.update({
  id: '/properties/new',
  path: '/properties/new',
  getParentRoute: () => AdminRoute,
} as any)
const V2AdminPropertiesIndexRoute = V2AdminPropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => V2AdminRoute,
} as any)
const V2AdminInquiriesIndexRoute = V2AdminInquiriesIndexRouteImport.update({
  id: '/inquiries/',
  path: '/inquiries/',
  getParentRoute: () => V2AdminRoute,
} as any)
const V2AdminPropertiesNewRoute = V2AdminPropertiesNewRouteImport.update({
  id: '/properties/new',
  path: '/properties/new',
  getParentRoute: () => V2AdminRoute,
} as any)
const AdminPropertiesIdEditRoute = AdminPropertiesIdEditRouteImport.update({
  id: '/properties/$id/edit',
  path: '/properties/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const V2AdminPropertiesIdEditRoute = V2AdminPropertiesIdEditRouteImport.update({
  id: '/properties/$id/edit',
  path: '/properties/$id/edit',
  getParentRoute: () => V2AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRoute
  '/apartments': typeof ApartmentsRoute
  '/blogs': typeof BlogsRoute
  '/builders': typeof BuildersRoute
  '/buy': typeof BuyRoute
  '/contact': typeof ContactRoute
  '/hive-verified': typeof HiveVerifiedRoute
  '/land': typeof LandRoute
  '/post-property': typeof PostPropertyRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/property/$slug': typeof PropertySlugRoute
  '/v2': typeof V2_rootRoute
  '/v2/about': typeof V2AboutRoute
  '/v2/admin': typeof V2AdminRouteWithChildren
  '/v2/apartments': typeof V2ApartmentsRoute
  '/v2/buy': typeof V2BuyRoute
  '/v2/contact': typeof V2ContactRoute
  '/v2/hive-verified': typeof V2HiveVerifiedRoute
  '/v2/land': typeof V2LandRoute
  '/v2/post-property': typeof V2PostPropertyRoute
  '/admin/': typeof AdminIndexRoute
  '/v2/': typeof V2IndexRoute
  '/admin/properties/new': typeof AdminPropertiesNewRoute
  '/v2/admin/login': typeof V2AdminLoginRoute
  '/v2/property/$slug': typeof V2PropertySlugRoute
  '/admin/inquiries/': typeof AdminInquiriesIndexRoute
  '/admin/properties/': typeof AdminPropertiesIndexRoute
  '/v2/admin/': typeof V2AdminIndexRoute
  '/admin/properties/$id/edit': typeof AdminPropertiesIdEditRoute
  '/v2/admin/properties/new': typeof V2AdminPropertiesNewRoute
  '/v2/admin/inquiries/': typeof V2AdminInquiriesIndexRoute
  '/v2/admin/properties/': typeof V2AdminPropertiesIndexRoute
  '/v2/admin/properties/$id/edit': typeof V2AdminPropertiesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/apartments': typeof ApartmentsRoute
  '/blogs': typeof BlogsRoute
  '/builders': typeof BuildersRoute
  '/buy': typeof BuyRoute
  '/contact': typeof ContactRoute
  '/hive-verified': typeof HiveVerifiedRoute
  '/land': typeof LandRoute
  '/post-property': typeof PostPropertyRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/property/$slug': typeof PropertySlugRoute
  '/v2': typeof V2IndexRoute
  '/v2/about': typeof V2AboutRoute
  '/v2/apartments': typeof V2ApartmentsRoute
  '/v2/buy': typeof V2BuyRoute
  '/v2/contact': typeof V2ContactRoute
  '/v2/hive-verified': typeof V2HiveVerifiedRoute
  '/v2/land': typeof V2LandRoute
  '/v2/post-property': typeof V2PostPropertyRoute
  '/admin': typeof AdminIndexRoute
  '/admin/properties/new': typeof AdminPropertiesNewRoute
  '/v2/admin/login': typeof V2AdminLoginRoute
  '/v2/property/$slug': typeof V2PropertySlugRoute
  '/admin/inquiries': typeof AdminInquiriesIndexRoute
  '/admin/properties': typeof AdminPropertiesIndexRoute
  '/v2/admin': typeof V2AdminIndexRoute
  '/admin/properties/$id/edit': typeof AdminPropertiesIdEditRoute
  '/v2/admin/properties/new': typeof V2AdminPropertiesNewRoute
  '/v2/admin/inquiries': typeof V2AdminInquiriesIndexRoute
  '/v2/admin/properties': typeof V2AdminPropertiesIndexRoute
  '/v2/admin/properties/$id/edit': typeof V2AdminPropertiesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRoute
  '/apartments': typeof ApartmentsRoute
  '/blogs': typeof BlogsRoute
  '/builders': typeof BuildersRoute
  '/buy': typeof BuyRoute
  '/contact': typeof ContactRoute
  '/hive-verified': typeof HiveVerifiedRoute
  '/land': typeof LandRoute
  '/post-property': typeof PostPropertyRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/property/$slug': typeof PropertySlugRoute
  '/v2/__root': typeof V2_rootRoute
  '/v2/about': typeof V2AboutRoute
  '/v2/admin': typeof V2AdminRouteWithChildren
  '/v2/apartments': typeof V2ApartmentsRoute
  '/v2/buy': typeof V2BuyRoute
  '/v2/contact': typeof V2ContactRoute
  '/v2/hive-verified': typeof V2HiveVerifiedRoute
  '/v2/land': typeof V2LandRoute
  '/v2/post-property': typeof V2PostPropertyRoute
  '/admin/': typeof AdminIndexRoute
  '/v2/': typeof V2IndexRoute
  '/admin/properties/new': typeof AdminPropertiesNewRoute
  '/v2/admin/login': typeof V2AdminLoginRoute
  '/v2/property/$slug': typeof V2PropertySlugRoute
  '/admin/inquiries/': typeof AdminInquiriesIndexRoute
  '/admin/properties/': typeof AdminPropertiesIndexRoute
  '/v2/admin/': typeof V2AdminIndexRoute
  '/admin/properties/$id/edit': typeof AdminPropertiesIdEditRoute
  '/v2/admin/properties/new': typeof V2AdminPropertiesNewRoute
  '/v2/admin/inquiries/': typeof V2AdminInquiriesIndexRoute
  '/v2/admin/properties/': typeof V2AdminPropertiesIndexRoute
  '/v2/admin/properties/$id/edit': typeof V2AdminPropertiesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/agents'
    | '/apartments'
    | '/blogs'
    | '/builders'
    | '/buy'
    | '/contact'
    | '/hive-verified'
    | '/land'
    | '/post-property'
    | '/privacy'
    | '/projects'
    | '/terms'
    | '/admin/login'
    | '/property/$slug'
    | '/v2'
    | '/v2/about'
    | '/v2/admin'
    | '/v2/apartments'
    | '/v2/buy'
    | '/v2/contact'
    | '/v2/hive-verified'
    | '/v2/land'
    | '/v2/post-property'
    | '/admin/'
    | '/v2/'
    | '/admin/properties/new'
    | '/v2/admin/login'
    | '/v2/property/$slug'
    | '/admin/inquiries/'
    | '/admin/properties/'
    | '/v2/admin/'
    | '/admin/properties/$id/edit'
    | '/v2/admin/properties/new'
    | '/v2/admin/inquiries/'
    | '/v2/admin/properties/'
    | '/v2/admin/properties/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agents'
    | '/apartments'
    | '/blogs'
    | '/builders'
    | '/buy'
    | '/contact'
    | '/hive-verified'
    | '/land'
    | '/post-property'
    | '/privacy'
    | '/projects'
    | '/terms'
    | '/admin/login'
    | '/property/$slug'
    | '/v2'
    | '/v2/about'
    | '/v2/apartments'
    | '/v2/buy'
    | '/v2/contact'
    | '/v2/hive-verified'
    | '/v2/land'
    | '/v2/post-property'
    | '/admin'
    | '/admin/properties/new'
    | '/v2/admin/login'
    | '/v2/property/$slug'
    | '/admin/inquiries'
    | '/admin/properties'
    | '/v2/admin'
    | '/admin/properties/$id/edit'
    | '/v2/admin/properties/new'
    | '/v2/admin/inquiries'
    | '/v2/admin/properties'
    | '/v2/admin/properties/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/agents'
    | '/apartments'
    | '/blogs'
    | '/builders'
    | '/buy'
    | '/contact'
    | '/hive-verified'
    | '/land'
    | '/post-property'
    | '/privacy'
    | '/projects'
    | '/terms'
    | '/admin/login'
    | '/property/$slug'
    | '/v2/__root'
    | '/v2/about'
    | '/v2/admin'
    | '/v2/apartments'
    | '/v2/buy'
    | '/v2/contact'
    | '/v2/hive-verified'
    | '/v2/land'
    | '/v2/post-property'
    | '/admin/'
    | '/v2/'
    | '/admin/properties/new'
    | '/v2/admin/login'
    | '/v2/property/$slug'
    | '/admin/inquiries/'
    | '/admin/properties/'
    | '/v2/admin/'
    | '/admin/properties/$id/edit'
    | '/v2/admin/properties/new'
    | '/v2/admin/inquiries/'
    | '/v2/admin/properties/'
    | '/v2/admin/properties/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgentsRoute: typeof AgentsRoute
  ApartmentsRoute: typeof ApartmentsRoute
  BlogsRoute: typeof BlogsRoute
  BuildersRoute: typeof BuildersRoute
  BuyRoute: typeof BuyRoute
  ContactRoute: typeof ContactRoute
  HiveVerifiedRoute: typeof HiveVerifiedRoute
  LandRoute: typeof LandRoute
  PostPropertyRoute: typeof PostPropertyRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRoute
  TermsRoute: typeof TermsRoute
  PropertySlugRoute: typeof PropertySlugRoute
  V2_rootRoute: typeof V2_rootRoute
  V2AboutRoute: typeof V2AboutRoute
  V2AdminRoute: typeof V2AdminRouteWithChildren
  V2ApartmentsRoute: typeof V2ApartmentsRoute
  V2BuyRoute: typeof V2BuyRoute
  V2ContactRoute: typeof V2ContactRoute
  V2HiveVerifiedRoute: typeof V2HiveVerifiedRoute
  V2LandRoute: typeof V2LandRoute
  V2PostPropertyRoute: typeof V2PostPropertyRoute
  V2IndexRoute: typeof V2IndexRoute
  V2PropertySlugRoute: typeof V2PropertySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/v2/__root': {
      id: '/v2/__root'
      path: '/v2'
      fullPath: '/v2'
      preLoaderRoute: typeof V2_rootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-property': {
      id: '/post-property'
      path: '/post-property'
      fullPath: '/post-property'
      preLoaderRoute: typeof PostPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/land': {
      id: '/land'
      path: '/land'
      fullPath: '/land'
      preLoaderRoute: typeof LandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hive-verified': {
      id: '/hive-verified'
      path: '/hive-verified'
      fullPath: '/hive-verified'
      preLoaderRoute: typeof HiveVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builders': {
      id: '/builders'
      path: '/builders'
      fullPath: '/builders'
      preLoaderRoute: typeof BuildersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartments': {
      id: '/apartments'
      path: '/apartments'
      fullPath: '/apartments'
      preLoaderRoute: typeof ApartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/': {
      id: '/v2/'
      path: '/v2'
      fullPath: '/v2/'
      preLoaderRoute: typeof V2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/v2/post-property': {
      id: '/v2/post-property'
      path: '/v2/post-property'
      fullPath: '/v2/post-property'
      preLoaderRoute: typeof V2PostPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/land': {
      id: '/v2/land'
      path: '/v2/land'
      fullPath: '/v2/land'
      preLoaderRoute: typeof V2LandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/hive-verified': {
      id: '/v2/hive-verified'
      path: '/v2/hive-verified'
      fullPath: '/v2/hive-verified'
      preLoaderRoute: typeof V2HiveVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/contact': {
      id: '/v2/contact'
      path: '/v2/contact'
      fullPath: '/v2/contact'
      preLoaderRoute: typeof V2ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/buy': {
      id: '/v2/buy'
      path: '/v2/buy'
      fullPath: '/v2/buy'
      preLoaderRoute: typeof V2BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/apartments': {
      id: '/v2/apartments'
      path: '/v2/apartments'
      fullPath: '/v2/apartments'
      preLoaderRoute: typeof V2ApartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/admin': {
      id: '/v2/admin'
      path: '/v2/admin'
      fullPath: '/v2/admin'
      preLoaderRoute: typeof V2AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/about': {
      id: '/v2/about'
      path: '/v2/about'
      fullPath: '/v2/about'
      preLoaderRoute: typeof V2AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$slug': {
      id: '/property/$slug'
      path: '/property/$slug'
      fullPath: '/property/$slug'
      preLoaderRoute: typeof PropertySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/v2/admin/': {
      id: '/v2/admin/'
      path: '/'
      fullPath: '/v2/admin/'
      preLoaderRoute: typeof V2AdminIndexRouteImport
      parentRoute: typeof V2AdminRoute
    }
    '/admin/properties/': {
      id: '/admin/properties/'
      path: '/properties'
      fullPath: '/admin/properties/'
      preLoaderRoute: typeof AdminPropertiesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries/': {
      id: '/admin/inquiries/'
      path: '/inquiries'
      fullPath: '/admin/inquiries/'
      preLoaderRoute: typeof AdminInquiriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/v2/property/$slug': {
      id: '/v2/property/$slug'
      path: '/v2/property/$slug'
      fullPath: '/v2/property/$slug'
      preLoaderRoute: typeof V2PropertySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/admin/login': {
      id: '/v2/admin/login'
      path: '/login'
      fullPath: '/v2/admin/login'
      preLoaderRoute: typeof V2AdminLoginRouteImport
      parentRoute: typeof V2AdminRoute
    }
    '/admin/properties/new': {
      id: '/admin/properties/new'
      path: '/properties/new'
      fullPath: '/admin/properties/new'
      preLoaderRoute: typeof AdminPropertiesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/v2/admin/properties/': {
      id: '/v2/admin/properties/'
      path: '/properties'
      fullPath: '/v2/admin/properties/'
      preLoaderRoute: typeof V2AdminPropertiesIndexRouteImport
      parentRoute: typeof V2AdminRoute
    }
    '/v2/admin/inquiries/': {
      id: '/v2/admin/inquiries/'
      path: '/inquiries'
      fullPath: '/v2/admin/inquiries/'
      preLoaderRoute: typeof V2AdminInquiriesIndexRouteImport
      parentRoute: typeof V2AdminRoute
    }
    '/v2/admin/properties/new': {
      id: '/v2/admin/properties/new'
      path: '/properties/new'
      fullPath: '/v2/admin/properties/new'
      preLoaderRoute: typeof V2AdminPropertiesNewRouteImport
      parentRoute: typeof V2AdminRoute
    }
    '/admin/properties/$id/edit': {
      id: '/admin/properties/$id/edit'
      path: '/properties/$id/edit'
      fullPath: '/admin/properties/$id/edit'
      preLoaderRoute: typeof AdminPropertiesIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/v2/admin/properties/$id/edit': {
      id: '/v2/admin/properties/$id/edit'
      path: '/properties/$id/edit'
      fullPath: '/v2/admin/properties/$id/edit'
      preLoaderRoute: typeof V2AdminPropertiesIdEditRouteImport
      parentRoute: typeof V2AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPropertiesNewRoute: typeof AdminPropertiesNewRoute
  AdminInquiriesIndexRoute: typeof AdminInquiriesIndexRoute
  AdminPropertiesIndexRoute: typeof AdminPropertiesIndexRoute
  AdminPropertiesIdEditRoute: typeof AdminPropertiesIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPropertiesNewRoute: AdminPropertiesNewRoute,
  AdminInquiriesIndexRoute: AdminInquiriesIndexRoute,
  AdminPropertiesIndexRoute: AdminPropertiesIndexRoute,
  AdminPropertiesIdEditRoute: AdminPropertiesIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface V2AdminRouteChildren {
  V2AdminLoginRoute: typeof V2AdminLoginRoute
  V2AdminIndexRoute: typeof V2AdminIndexRoute
  V2AdminPropertiesNewRoute: typeof V2AdminPropertiesNewRoute
  V2AdminInquiriesIndexRoute: typeof V2AdminInquiriesIndexRoute
  V2AdminPropertiesIndexRoute: typeof V2AdminPropertiesIndexRoute
  V2AdminPropertiesIdEditRoute: typeof V2AdminPropertiesIdEditRoute
}

const V2AdminRouteChildren: V2AdminRouteChildren = {
  V2AdminLoginRoute: V2AdminLoginRoute,
  V2AdminIndexRoute: V2AdminIndexRoute,
  V2AdminPropertiesNewRoute: V2AdminPropertiesNewRoute,
  V2AdminInquiriesIndexRoute: V2AdminInquiriesIndexRoute,
  V2AdminPropertiesIndexRoute: V2AdminPropertiesIndexRoute,
  V2AdminPropertiesIdEditRoute: V2AdminPropertiesIdEditRoute,
}

const V2AdminRouteWithChildren =
  V2AdminRoute._addFileChildren(V2AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AgentsRoute: AgentsRoute,
  ApartmentsRoute: ApartmentsRoute,
  BlogsRoute: BlogsRoute,
  BuildersRoute: BuildersRoute,
  BuyRoute: BuyRoute,
  ContactRoute: ContactRoute,
  HiveVerifiedRoute: HiveVerifiedRoute,
  LandRoute: LandRoute,
  PostPropertyRoute: PostPropertyRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRoute,
  TermsRoute: TermsRoute,
  PropertySlugRoute: PropertySlugRoute,
  V2_rootRoute: V2_rootRoute,
  V2AboutRoute: V2AboutRoute,
  V2AdminRoute: V2AdminRouteWithChildren,
  V2ApartmentsRoute: V2ApartmentsRoute,
  V2BuyRoute: V2BuyRoute,
  V2ContactRoute: V2ContactRoute,
  V2HiveVerifiedRoute: V2HiveVerifiedRoute,
  V2LandRoute: V2LandRoute,
  V2PostPropertyRoute: V2PostPropertyRoute,
  V2IndexRoute: V2IndexRoute,
  V2PropertySlugRoute: V2PropertySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
